## Basic Configuration

baseurl = "/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Marium Tapal"
title = "Marium Tapal"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
#enableRobotsTXT = true

## Site Settings
[params]
author = "Marium Tapal"
intro = "Student at Smith College"
description = "Double Majoring in Statistical and Data Sciences & Mathematics"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "mariumtapal"
linkedin = "mariumtapal"
twitter = "mariumtapal"
email = "mariumtapal@gmail.com"

## Extras
[params.extra]
copyright = "&copy; 2020 Marium Tapal"
#poweredby = true
#highlightjs = true
#socialmarkup = true
#toc = true
#displayrssicon = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "blog"
    weight = 300
    identifier = "blog"
    url = "/blog/"

