[build]
command = "hugo"
publish = "public"
[context.production.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.101.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.101.0"

# netlify.toml
# source: https://www.garrickadenbuie.com/blog/blogdown-netlify-new-post-workflow/#netlify-toml
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"