---
title: "Summer 2020 Data Science Internship"
author: "Marium Tapal"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
categories: []
tags: []
---

Due to the COVID-19 pandemic, I ended spending my summer at home in Pakistan. In the summer, Pakistan is 9 hours ahead of Eastern United States time. From June 1 to July 24, I worked remotely with Professor Albert Y. Kim. 

Every Monday evening (and other times as needed), I would meet with Professor Kim over Zoom to discuss things that were missed over Slack, review completed tasks since the last meeting, and devise a plan for the upcoming week.  

As part of my internship, I was working on two maain projects:

- the [`fivethirtyeight`](#fivethirtyeight) R package
- the [`ModernDive`](#moderndive) book + R package + labs website

# Structure



## `fivethirtyeight` R package {#fivethirtyeight}
- drat package

## `ModernDive` book {#moderndive}

## General takeaways
- reproducibility
- being organized
- working with branches/forks
- when to create organizations on GitHub
- collaboration
- outward facing work vs inward
- establishing a routine



## preperation

**How did your academic studies help to prepare you for this internship? How will this experience inform your future studies when you return to Smith?**

The courses I have taken and the special studies I did last semester prepared me well for this. Once I return to Smith, I plan to undertake personal projects, take more courses, and use the skills I learnt during this internship.

# Praxis Questions

**Describe the primary duties, tasks and projects of your internship. What were the most significant and/or impactful experiences? (minimum 300 words)**

My internship with Professor Kim was to primarily wrap-up two of his data science related projects. 1. the fivethirtyeight R package and 2. the ModernDive textbook. 

In the fivethirtyeight R package, my job was to further clean the package by writing code such that it is able to be hosted fully on The Comprehensive R Archive Network (CRAN). The package was only partially hosted as it exceeded the maximum 5MB size required by CRAN. Additionally, I was given the task of creating a product that is future-proof: i.e. such that future datasets are able to be hosted as well without extraneous work. I was able to fulfill this task using the drat functionality. 

The ModernDive textbook is a textbook for introductory statistics and data science which is available in print and as an open-source online version. Along with the textbook, there is the moderndive R package and a website that houses sample problem sets and projects as well as tips and tricks. I was assigned to clean up the R code written for the online version of the textbook to improve it for reproducibility. For example, I replaced the hard-coded data values with dynamic data values. My other task was to work on simplifying and organizing the website for a better user interface. The third task was to assist in solving some issues that came up with the accompanying moderndive R package, such as some functions in the package depended on the other functions and packages written by other authors. Changes to these meant we had to update our functions - which was my task. 

I learned new things through all of the different tasks and projects I was assigned to, but the most impactful were the following:

* Learning how to think in the seat of the user of the products —  so create solutions with the user experience in mind 
* While I was sort of familiar with R package development, I had never worked on updating a previously used package. I had to take into account that the user experience should not change much and be very difficult
* Researching into new technologies and using them was extremely helpful. Searching for what others have done and what I could do with my work
* Fixing issues, debugging and passing standard checks in coding


**What skills did you use most often in your work? What new skills and abilities did you develop and how will they be useful to you in the future? (minimum 150 words)**

Through this summer internship as a data science intern, a lot of the skills I used and developed were technical, but just as is the case with working in real life, there were some key personal and transferable skills that I believe I gained this summer.

Technical Skills:

* Software engineering in data science that is, working in a data science-focused language, R, to create software
* Version control with Git and GitHub
* Working in GitHub branches and organizations for collaboration
* Setting and running checks in various platforms such as with Travis CI and GitHub Actions
* Debugging and fixing broken code
* Understanding basic HTML and how that works in collaboration with R
* Developing R packages and updating them

Non-Tech Skills:

* Working remotely and collaborating 
* Structuring time so that some work hours overlap with work hours in the US (I was 9 hours ahead of my supervisor)
* Communicating via Slack and Zoom
* Asking appropriate questions 

All of the skills above, I believe are quite essential for a career in the data science industry. Working through a pandemic, remotely, taught adaptability and that is something that can be transferred over to other situations in the future.

**Describe any difficulties or challenges you experienced and how you addressed them over the course of your internship.**

The biggest struggle was the 9-hour time zone difference since I was at home in Pakistan because of the COVID-19 pandemic. We worked this out by having meetings early in the a.m. Eastern Time, and in the evening my time. Other issues included working around the structural methods in the R programming language -- these issues were not exactly our issues but as users of the language, there were some challenges. To overcome these, we looked for different ways to address the limitations such as workaround functions.

**Describe any "critical moments" and/or experiences that shifted your perceptions of the world of work, the field, yourself as a professional, and/or the organization for which you interned.**

When my work was accepted through pull requests, I knew I can do these things. My work is live and thousands of people all across the world use it and look at it which is an incredible feeling. My outlook on working in academia and doing research has changed in the sense that it is something that I would like to do simultaneously while working in industry.

**Having observed and engaged with professionals, what makes one "successful"?**

I really believe that enjoying what you’re doing, having passion for it makes one "successful". But in saying that, having structure is very important and so is living life simultaneously by doing things you enjoy of work.

**How did your academic studies help to prepare you for this internship? How will this experience inform your future studies when you return to Smith?**

The courses I have taken and the special studies I did last semester prepared me well for this. Once I return to Smith, I plan to undertake personal projects, take more courses, and use the skills I learnt during this internship.

**Pick an example of a project or task that didn't go well during your internship. What went wrong? What did you do when you found yourself in this situation? What could or would you have done differently?**

In the `fivethirtyeight` R package, one of my assigned tasks was to modify the package to adhere to the CRAN size restrictions. We ended up deciding to use the `drat` package to this. In this, something that Professor Kim wanted was to autoload the newly made add-on `fivethirtyeightdata` package. Even after many tries, we realised that this wasn't possible. While this was something that went wrong, it wasn't something that was our fault. It is a structural thing in the R programming language. We decided that it was okay that the user had to manually load this package, but retrospectively, perhaps we could have used a different approach to modify the package to adhere to the CRAN size restrictions and would have not have run into this issue.


**In what was did your internship contribute to your larger and/or academic goals? How have your goals shifted? Where do you see yourself headed now that you didn't before?**

This internship provided me a great experience working within academia and made me realise that this type of work is something I would like to do in the future, perhaps in conjunction with work in the industry since a lot of the work I did was user-facing. I also came to the conclusion of taking more varied coursework in statistics and data sciences in my remaining time at Smith which are not required to finish the major. Also to not be intimidated at opportunities that seem out of reach. The only reason I was able to get this internship and do so well was because of the **Advanced Programming in R** course I took last fall that initially scared me as I was one of very few sophomores amongst mostly seniors and juniors.  

**We have several endowed funds that are used specifically for Praxis-Funded internships. It is likely that the Praxis fund assigned to your internship has been donated by a Smith alumna. Please share 3 highlights from your experience. What do you know about yourself now as a professional? In what was did smith prepare you for your internship? Please note your response may be shared with donors.**

The 3 highlights:
1. Merging my work into the official release and published branches on GitHub
2. Appreciation for all my work from Professor Kim and also his collaborators on the projects I worked on
3. Learning so many new tools (concepts and practices) in data science 

I know that as a professional I can do a lot of things that I think I can't, and if I don't know how, I have the ability to learn them. The courses I have taken, the experiences I have been given, and the relationships I have formed with Professors at Smith in my two years at Smith so far, prepared me very well for this internship.
